#!/bin/bash
echo "🔧 Supabase Connection String Update Guide"
echo "=========================================="
echo ""
echo "Current (Pooler - causing issues):"
echo "  postgresql://postgres.dxfizbqyjuyemdtncezd:don-paolo123@aws-1-eu-north-1.pooler.supabase.com:5432/postgres"
echo ""
echo "New (Direct - fixes the issue):"
echo "  postgresql://postgres:don-paolo123@db.dxfizbqyjuyemdtncezd.supabase.co:5432/postgres"
echo ""
echo "📋 Steps to Update:"
echo "1. Go to Render Dashboard → Your Service → Environment"
echo "2. Find: ConnectionStrings__DefaultConnection"
echo "3. Replace with the NEW connection string above"
echo "4. Save - Render will auto-redeploy"
echo ""
echo "✅ After deployment, user updates will persist in Supabase!"
